services:
  webapp:
     image: infracloudio/csvserver:latest
     volumes:
       - ./inputFile:/csvserver/inputdata
     container_name: csvsrv
     ports:
       - 9393:9300
     environment:
       - CSVSERVER_BORDER=Orange
